volumes:
  meilisearch:

services:
  meilisearch:
    image: getmeili/meilisearch
    volumes:
      - "meilisearch:/meili_data"
    restart: unless-stopped

  starsearch:
    image: ghcr.io/zekrotja/starsearch:latest
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      RUST_LOG: info,hyper=warn,isahc=warn,handlebars=warn
      SS_MEILISEARCH_URL: http://meilisearch:7700
      SS_GITHUB_USERNAME: zekroTJA
      SS_GITHUB_APITOKEN: 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
      SS_SKIP_INITIAL_SCRAPE: true
