volumes:
  meilisearch:

services:
  meilisearch:
    image: getmeili/meilisearch
    volumes:
      - "meilisearch:/meili_data"
    restart: unless-stopped

  starsearch:
    image: ghcr.io/zekrotja/starsearch:latest
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      # Logger configuration
      RUST_LOG: info,hyper=warn,isahc=warn,handlebars=warn
      # The address of your meilisearch instance. In this case, it
      # is included in this stack, so leave this as-is.
      SS_MEILISEARCH_URL: http://meilisearch:7700
      # The name of the GitHub user whose starred repositories shall
      # be scraped.
      SS_GITHUB_USERNAME: zekroTJA
      # A GitHub API token. This is not necessarily required, but with
      # a larger ammount of repositories to be scraped, you will run into
      # rate limiting issues without using an API token.
      # You can obtain a token from here:
      # https://github.com/settings/personal-access-tokens
      SS_GITHUB_APITOKEN: <your GitHub API token>
      # Set this to true to disable scraping your starred repositories
      # on application startup.
      SS_SKIP_INITIAL_SCRAPE: true
      # Interval (in seconds) in which a "fast" scrape is performed.
      # That means that only new stars are indexed instead of re-indexing
      # all starred repositories.
      SS_SCRAPE_FAST_INTERVAL_SECONDS: 850
      # Interval (in seconds) in which a "full" scrape is performed.
      # That means that all starred repositories are fetched and re-indexed.
      # Depending on the size of your library, this process can take some time.
      # It is recommended to set both intervals in a way where both processed
      # won't start on the same time.
      SS_SCRAPE_FULL_INTERVAL_SECONDS: 86400
