# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: run

  run:
    cmds:
      - cargo run -p starsearch-server

  release:
    cmds:
      - cargo build --release

  dev-env-up:
    aliases: [dev-env]
    cmds:
      - docker compose -f docker-compose.dev.yml up -d

  dev-env-down:
    cmds:
      - docker compose -f docker-compose.dev.yml up down

  docker-compose:
    aliases: [dc]
    cmds:
      - docker compose -f docker-compose.dev.yml {{.CLI_ARGS}}
